services:
    ph.event_listener.send_subscription_payload:
        class: PH\Bundle\CoreBundle\EventSubscriber\SendSubscriptionPayloadListener
        arguments:
            - "@ph.payload_sender.subscription"
        tags:
            - { name: kernel.event_listener, event: ph.subscription.post_create, method: sendPayload }
            - { name: kernel.event_listener, event: ph.subscription.post_update, method: sendPayload }

    ph.event_listener.assign_subscription_token:
        class: PH\Bundle\CoreBundle\EventListener\AssignSubscriptionTokenListener
        arguments:
            - "@ph.subscription_token_assigner"
        tags:
            - { name: kernel.event_listener, event: ph.subscription.pre_create, method: assignToken }

    ph.event_listener.populate_subscription:
        class: PH\Bundle\CoreBundle\EventListener\PopulateSubscriptionBasedOnStripePlanListener
        tags:
            - { name: kernel.event_listener, event: ph.subscription.pre_create, method: populate }

    ph.event_listener.create_stripe_intent:
        class: PH\Bundle\CoreBundle\EventListener\CreateStripePaymentIntentListener
        tags:
            - { name: kernel.event_listener, event: ph.subscription.pre_create, method: createIntent }
